# Generated by Django 2.0.3 on 2018-03-31 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_desc', models.CharField(max_length=500)),
                ('correct', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='course.subject'),
        ),
        migrations.AddField(
            model_name='answer',
            name='option_que',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='course.questions'),
        ),
        migrations.AddField(
            model_name='answer',
            name='option_sub',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='course.subject'),
        ),
    ]
