# Generated by Django 2.0 on 2017-12-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poc_teaching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
